### PR TITLE
Add mint themes and icons

### PR DESCRIPTION
**Pull request by Pogogo007**

### CODE REVIEW

**Comment by swapnanil1** [comment]
Hello @Pogogo007,
I'm a newcomer to Cachyos, and I have to say that custom package builds is something that attracted me to your distro. I noticed that I no longer see the mint-themes PKGBUILD and some others visible earlier in the master branch. What makes them no longer visible after adding the PKGBUILDs in the master? Are the package builds viewable only by people who self-host the repository, or is there another reason they vanished?

Thanks for your help!

**Comment by ptr1337** [comment]
Hi,

PKGBUILDs which do not get notified compared to the AUR/Arch packges dont need to be added. Packages in the AUR gets automatically updated and does not require manual maintainance from our side

**Comment by swapnanil1** [comment]
Thanks for the quick response! Is there a set of commands or links to view all the AUR packages that CachyOS builds and ships?

**Comment by ptr1337** [comment]
> Thanks for the quick response! Is there a set of commands or links to view all the AUR packages that CachyOS builds and ships?

We do not have a complete list, but most AUR packages you can find here:
https://mirror.cachyos.org/repo/x86_64/cachyos/

**Pull request closed without merging**
