### PR TITLE
mesa: Improve RT performance in RADV driver and fix DEQP crash

### PR DESCRIPTION
**Pull request by 1Naim**
Cherrypick 2 patches that improve performance in general and when ray tracing respectively.

These 2 patches [[1](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/25576)] [[2](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/31443)] were cherry picked in response to my comment I made https://github.com/CachyOS/CachyOS-PKGBUILDS/pull/328#issuecomment-2326311069.

Edit:
The first patch doesn't seem to do anything so I'm just going to cherrypick the 2nd one as it fixes wayland sessions crashing too x).

### CODE REVIEW

**Comment by ms178** [comment]
Just FYI, the second one got merged into mesa-git an hour ago. You might also take a look at 28973 and 20275. As CachyOS adopted zlib-ng and also compiles with march, both might yield some benefits. I've used these both locally for some time.

**Comment by 1Naim** [comment]
28973: We don't need to cherry-pick this because we are already using zlib-ng-compat.

20275: I'm hesitant on adding a closed PR, but I'll look into it tomorrow as there is a chance this has been merged in the form of another MR.

**Comment by ptr1337** [comment]
> Just FYI, the second one got merged into mesa-git an hour ago. You might also take a look at 28973 and 20275. As CachyOS adopted zlib-ng and also compiles with march, both might yield some benefits. I've used these both locally for some time.

One got closed, the other is still drafted

**Comment by ptr1337** [comment]
> 28973: We don't need to cherry-pick this because we are already using zlib-ng-compat.

Native zlib-ng is faster tho. But yeah, as long its a draft wont happen

**Comment by ms178** [comment]
> > Just FYI, the second one got merged into mesa-git an hour ago. You might also take a look at 28973 and 20275. As CachyOS adopted zlib-ng and also compiles with march, both might yield some benefits. I've used these both locally for some time.
> 
> One got closed, the other is still drafted

I wouldn't derive too much from the status alone. Marek closed it because he didn't want to put much more time into it, the MR is still useful though on what it brings to the table, especially since CachyOS would make use of that code path.

**Comment by 1Naim** [comment]
> These 2 patches [[1](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/25576)] [[2](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/31443)] were cherry picked in response to my comment I made [#328 (comment)](https://github.com/CachyOS/CachyOS-PKGBUILDS/pull/328#issuecomment-2326311069).

These 2 patches are now merged upstream. It should be relatively safe to cherry-pick them here.

I've also cherrypicked another patch that fixes a DEQP that will likely be backported to 24.2 branch as the regression also affects this branch.

**Review by ptr1337 — APPROVED** [review]

**Pull request merged**
