### PR TITLE
[pacman] Add commented ILoveCandy

### PR DESCRIPTION
**Pull request by TheWyn**
PrettyProgressBar patch includes an option for ILoveCandy and isn't included in the config.  All the other options are already added here.

### CODE REVIEW

**Comment by 1Naim** [comment]
ILoveCandy is part of core pacman but yeah we can add this to the makepkg.conf

**Review by 1Naim — APPROVED** [review]

**Comment by ptr1337** [comment]
Why do we want this? This is actually already set in the install pacman config:
https://github.com/CachyOS/CachyOS-Live-ISO/blob/master/archiso/airootfs/etc/pacman-more.conf#L35

**Comment by 1Naim** [comment]
My thinking was mainly for posterity in the pacman.conf provided by the package itself, considering all the other options have the comments too.

**Comment by TheWyn** [comment]
It is not included in the .pacnew whenever pacman has an update

**Comment by ptr1337** [comment]
Thats an argument

**Review by ptr1337 — APPROVED** [review]

**Review by 1Naim — CHANGES_REQUESTED** [review]
This flew under my radar, but please update the checksums too. You can do this with `updpkgsums` and `makepkg --printsrcinfo > .SRCINFO` to update .SRCINFO

**Review by vnepogodin — APPROVED** [review]

**Review by 1Naim — APPROVED** [review]
Thanks!

**Pull request merged**
