### PR TITLE
proton-cachyos: Proton 9.0 port of fastsync.patch

### PR DESCRIPTION
**Pull request by Username404-59**
Note: I don't use CachyOS but I ported this on my gentoo machine so I figured I might as well submit it
Needs testing and probably a bit of cleanup

### CODE REVIEW

**Comment by ptr1337** [comment]
Wow! Thanks for porting.

This is the port of the fastsync patch and not NTSync , right?

I will start testing today.

**Comment by Username404-59** [comment]
> This is the port of the fastsync patch and not NTSync , right?

Yes this is basically just the existing patch with resolved merge conflicts

**Comment by ptr1337** [comment]
> > This is the port of the fastsync patch and not NTSync , right?
> 
> Yes, this is basically just the existing patch with resolved merge conflicts

Very cool. I will start locally a build and will test it.
This patch also needs to be rebased, if we want to put it behind a env (e.G disabled as default, enabled via env variable):
https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/master/proton-cachyos/proton-cachyos/disable-fastsync.patch#L47-L55

But I can do this later.

**Comment by ptr1337** [comment]
@Username404-59 

I have tested it locally and it appears to work correctly, thanks!

Could you also apply this diff:
``diff
diff --git a/proton-cachyos/proton-cachyos/PKGBUILD b/proton-cachyos/proton-cachyos/PKGBUILD
index 8a7d1ba..aadb9a8 100644
--- a/proton-cachyos/proton-cachyos/PKGBUILD
+++ b/proton-cachyos/proton-cachyos/PKGBUILD
@@ -8,12 +8,12 @@ _optimize_v3=${_optimize_v3-y}
 _optimize_v4=${_optimize_v4-}
 
 pkgname=proton-cachyos
-_srctag=9.0-20240315
+_srctag=9.0-20240320
 _commit=
 pkgver=9.0
 _geckover=2.47.4
 _monover=9.0.0
-pkgrel=4
+pkgrel=6
 pkgdesc="Compatibility tool for Steam Play based on Wine and additional components, experimental branch with extra CachyOS flavour"
 url="https://github.com/cachyos/proton-cachyos"
 arch=(x86_64 x86_64_v3)
diff --git a/proton-cachyos/proton-cachyos/disable-fastsync.patch b/proton-cachyos/proton-cachyos/disable-fastsync.patch
index af68e42..606c152 100644
--- a/proton-cachyos/proton-cachyos/disable-fastsync.patch
+++ b/proton-cachyos/proton-cachyos/disable-fastsync.patch
@@ -44,12 +44,3 @@ index f93f545f..2e0199f0 100755
          if "nowritewatch" in self.compat_config:
              self.env["WINE_DISABLE_WRITE_WATCH"] = "1"
  
-@@ -1587,6 +1598,8 @@ class Session:
-             f.write("\tWINEESYNC=\"" + self.env["WINEESYNC"] + "\" \\\n")
-         if "WINEFSYNC" in self.env:
-             f.write("\tWINEFSYNC=\"" + self.env["WINEFSYNC"] + "\" \\\n")
-+        if "WINE_DISABLE_FAST_SYNC" in self.env:
-+            f.write("\tWINE_DISABLE_FAST_SYNC=\"" + self.env["WINE_DISABLE_FAST_SYNC"] + "\" \\\n")
-         if "SteamGameId" in self.env:
-             f.write("\tSteamGameId=\"" + self.env["SteamGameId"] + "\" \\\n")
-         if "SteamAppId" in self.env:

```

**Comment by ptr1337** [comment]
Also, would it be possible that you put your gpg key to github?

Currently the commits are signed but not verified.
image

**Comment by Username404-59** [comment]
> Also, would it be possible that you put your gpg key to github?
> 
> Currently the commits are signed but not verified.

Oh yeah I used one with a different email which is why it's unverified
I'll force-push resigned ones

**Review by ptr1337 — APPROVED** [review]
LGTM

Thanks!

**Pull request merged**
