### PR TITLE
mesa: 24.3.1

### PR DESCRIPTION
**Pull request by 1Naim**
Removed the b2sums array. Refer to commit log for rationale. It's controversial so let me know if you don't want this.

### CODE REVIEW

**Comment by ptr1337** [comment]
Removing sha256 would be better and keeping b2 :)

**Comment by 1Naim** [comment]
> Removing sha256 would be better and keeping b2 :)

Any reasons for this? https://wiki.archlinux.org/title/PKGBUILD#Integrity:

> The checksum type and values should always be those provided by upstream, such as in release announcements.

As far as I can see in https://docs.mesa3d.org/relnotes/24.3.1.html, mesa doesn't provide b2 checksums. Although now that I see it again, we should probably use sha512 instead since that's preferred over sha256.

**Comment by vnepogodin** [comment]
> > Removing sha256 would be better and keeping b2 :)
> 
> Any reasons for this? https://wiki.archlinux.org/title/PKGBUILD#Integrity:
> 
> > The checksum type and values should always be those provided by upstream, such as in release announcements.
> 
> As far as I can see in https://docs.mesa3d.org/relnotes/24.3.1.html, mesa doesn't provide b2 checksums. Although now that I see it again, we should probably use sha512 instead since that's preferred over sha256.

Weää I think we should keep as arch there

**Comment by 1Naim** [comment]
> > > Removing sha256 would be better and keeping b2 :)
> > 
> > 
> > Any reasons for this? https://wiki.archlinux.org/title/PKGBUILD#Integrity:
> > > The checksum type and values should always be those provided by upstream, such as in release announcements.
> > 
> > 
> > As far as I can see in https://docs.mesa3d.org/relnotes/24.3.1.html, mesa doesn't provide b2 checksums. Although now that I see it again, we should probably use sha512 instead since that's preferred over sha256.
> 
> Well I think we should keep as arch there

Sure, I'll just drop the last commit then so it's not blocking the version update.

**Review by ptr1337 — APPROVED** [review]

**Pull request merged**
