### PR TITLE
proton-cachyos: update nvapi-optical-flow.patch

### PR DESCRIPTION
**Pull request by silvanshade**
This PR updates `proton-cachyos` with the latest changes from the nvapi optical flow PR.

### CODE REVIEW

**Review by ptr1337 — CHANGES_REQUESTED** [review]
Could you bump the pkgrel to 3?

Besides that looks fine, thank you!

**Comment by silvanshade** [comment]
> Could you bump the pkgrel to 3?

Done.

By the way, one thing I noticed is that I had a build failure the first time due to a missing Rust toolchain for i686.

I had to run the following and rebuild for it to succeed:

```
RUSTUP_TOOLCHAIN=stable rustup target add i686-unknown-linux-gnu
```

I'm guessing this doesn't show up in the automated environment if the full Rust environment is already set up beforehand.

Should I create another PR to add this step to `prepare`?

**Comment by ptr1337** [comment]
Thank you!
Looks good now.

On archlinux/cachyos we are using the lib32-rust-libs, which should provide support for this. Users, which are using rustup need to manually the lib32 compiler.

**Review by ptr1337 — APPROVED** [review]

**Comment by gilvbp** [comment]
https://github.com/jp7677/dxvk-nvapi/pull/213 New changes

**Pull request merged**
