### PR TITLE
cachy-browser: Rework PKGBUILD and drop librewolf stuff

### PR DESCRIPTION
**Pull request by ptr1337**
This reworks the cachy-browser PKGBUILD and patches.

We are dropping the librewolf patches and go for a "tuned" firefox version, which provides a more secure and faster config.
The gentoo patches will be still applied.

Generally, this is done since librewolf does update their patches in a very slow cycle and specially if CVE's or equal are present, we can not push when we want.

Drawsbacks:
- Loosing the "Cachy" Page for various setting
- Some less security directly in the patches

Im  also converting the PKGBUILD to follow the upstream archlinux PKGBUILD, so that this keeps same as possible.
Currently we can not compile cachy-browser for higher architectures, because LLVM 18 has a bug.

This will be fixed as soon archlinux does push LLVM19 into the repository.
Outisde of that, we are using only ThinLTO instead of "cross,full", which speeds up the compilation, while having barely performance looses.
Fixes: https://github.com/CachyOS/CachyOS-PKGBUILDS/issues/337
Signed-off-by: Peter Jung <admin@ptr1337.dev>

### CODE REVIEW

**Review by sirlucjan — APPROVED** [review]
Tested-by: Piotr Gorski [piotrgorski@cachyos.org](mailto:piotrgorski@cachyos.org)

**Comment by ventureoo** [comment]
Can we accomplish https://github.com/CachyOS/CachyOS-PKGBUILDS/issues/337 in this case?

**Comment by ptr1337** [comment]
> Can we accomplish #337 in this case?

Done

**Comment by ventureoo** [comment]
> > Can we accomplish #337 in this case?
> 
> Done

Thanks, can also be labeled as `Fixes: https://github.com/CachyOS/CachyOS-PKGBUILDS/issues/337`.

**Pull request merged**
