### PR TITLE
clang: Build with PGO and ThinLTO

### PR DESCRIPTION
**Pull request by ptr1337**
Benchmarks:

@ptr1337 , 9950X
```
PGO ThinLTO Clang, modprobed.db kernel, ThinLTO enabled
________________________________________________________
Executed in  175.51 secs    fish           external
   usr time   39.54 mins    0.00 micros   39.54 mins
   sys time    2.74 mins  133.00 micros    2.74 mins

GCC built Clang from znver4 repository
________________________________________________________
Executed in  195.74 secs    fish           external
   usr time   49.87 mins    0.00 micros   49.87 mins
   sys time    2.78 mins  142.00 micros    2.78 mins
```

Yuby, 5800X
```
CachyOS kernel + ThinLTO + Nvidia + modprobed

clang 18.1.8-2 8:21
clang 18.1.8-3 6:56
```

@1Naim Mesa ThinLTO Compilation
```
Optimized clang + llvm
Executed in   16.77 mins    fish           external
   usr time  165.51 mins    0.00 micros  165.51 mins
   sys time    4.39 mins  658.00 micros    4.39 mins

Unchanged clang + llvm
Executed in   20.26 mins    fish           external
   usr time  212.03 mins    0.42 millis  212.03 mins
   sys time    4.69 mins    1.43 millis    4.69 mins
```

### CODE REVIEW

**Comment by ptr1337** [comment]
@1Naim
```
sudo pacman -U https://archive.cachyos.org/clang-pgo-thinlto/clang-18.1.8-3-x86_64_v3.pkg.tar.zst
```

**Comment by 1Naim** [comment]
save my cpu....

**Comment by ptr1337** [comment]
YUBY from Discord had following results:
```
CachyOS kernel + ThinLTO + Nvidia + modprobed

clang 18.1.8-2 8:21
clang 18.1.8-3 6:56
```

**Comment by ptr1337** [comment]
Made a kernel compilation, with modprobed db + ThinLTO enabled.
The packaging time and pahole is there also included, but its quite faster:
```
PGO ThinLTO Clang, modprobed.db kernel, ThinLTO enabled
________________________________________________________
Executed in  175.51 secs    fish           external
   usr time   39.54 mins    0.00 micros   39.54 mins
   sys time    2.74 mins  133.00 micros    2.74 mins

GCC built Clang from znver4 repository
________________________________________________________
Executed in  195.74 secs    fish           external
   usr time   49.87 mins    0.00 micros   49.87 mins
   sys time    2.78 mins  142.00 micros    2.78 mins
``` 

Means a 10% improvement for the whole kernel. This seems like a major win.

**Comment by 1Naim** [comment]
Building mesa with clang + ThinLTO
```
Optimized clang + llvm
Executed in   16.77 mins    fish           external
   usr time  165.51 mins    0.00 micros  165.51 mins
   sys time    4.39 mins  658.00 micros    4.39 mins

Unchanged clang + llvm
Executed in   20.26 mins    fish           external
   usr time  212.03 mins    0.42 millis  212.03 mins
   sys time    4.69 mins    1.43 millis    4.69 mins
```

**Pull request merged**
