### PR TITLE
wine-cachyos: Enable LTO compilation for all native libraries

### PR DESCRIPTION
**Pull request by whrvt**
`lto-fixup.patch` is a rebase of a [patch](https://github.com/openglfreak/wine-tkg-userpatches/blob/df0a89aec388b23a8a82dca6d53e65d25c3a8f86/patches/9999-diffs/lto-fixup.patch) by Torge Matthies, which supersedes [server: Enable link-time optimization](https://github.com/CachyOS/wine-cachyos/commit/cc9ebe323b825db218fb3c257374e81fb5ebc4ed) by allowing all native modules (i.e. modules compiled without mingw) to be compiled with LTO, not just wineserver. 

The relevant compilation flags are added to the PKGBUILD.

### CODE REVIEW

**Comment by ptr1337** [comment]
This is already included.

**Comment by loathingKernel** [comment]
I am positive about using using LTO for everything instead of wineserver only. My issue in the current form is that it modifies the compilation flags in the PKGBUILD. This cannot work for the proton PKGBUILD, it has to be done in Proton's makefile instead. We can keep this open for discussions but we gonna have to apply it independently.

**Comment by ptr1337** [comment]
@whrvt Could you maybe rebase? I would like to test this out on the standalone wine-cachyos, before proceeding with the complete proton.

**Review by ptr1337 — APPROVED** [review]
Thanks! I gonna push this today out and we will see, if any bad reports are coming.

**Comment by ptr1337** [comment]
Has been pushed to cachyos-v3, cachyos-v4 and cachyos-znver4

**Pull request merged**
